name: Build and Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Extract versions from gradle
        id: gradle_versions
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload build artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/*.jar

      - name: Create release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/libs/*.jar